### ISSUE TITLE
figure out a way to merge all wiki commands

### ISSUE THREAD

**Issue by adrifcastr** [adrifcastr/Gideon#17]

**Comment by adrifcastr** [comment]
merged with 6bdc4c6737c677cd81f76c4dc7c5ab57a4870ec7 todo: make it better.

**Comment by adrifcastr** [comment]
fixed itself?

**Comment by adrifcastr** [comment]
Un-fixed itself.

**Comment by adrifcastr** [comment]
todo: make the bot accept `!wikidc` instead of `!wiki dc` etc..

**Comment by MBR-0001** [comment]
Solved in #28
